# Generated by Django 5.1.1 on 2024-09-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Dessert", "Dessert"),
                            ("Main Course", "Main Course"),
                            ("Breakfast", "Breakfast"),
                            ("Vegetarian", "Vegetarian"),
                        ],
                        max_length=50,
                    ),
                ),
                ("preparation_time", models.IntegerField(help_text="Time in minutes")),
                ("cooking_time", models.IntegerField(help_text="Time in minutes")),
                ("servings", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
